services:
  flask-app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - /srv/rendering:/data/rendering
    environment:
      - FLASK_APP=app:app
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1

